!!python/object/apply:collections.OrderedDict
- - - activation_fn
    - tanh
  - - batch_size
    - 1024
  - - buffer_capacity
    - 84000
  - - cg_max_steps
    - 20
  - - ent_coef
    - 0.0006000000000000001
  - - epsilon
    - 0.35
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 0.089689672362115
  - - n_critic_updates
    - 10
  - - n_envs
    - 8
  - - n_steps
    - 2048
  - - n_timesteps
    - 100000
  - - net_arch
    - medium
  - - policy
    - MlpPolicy
  - - replay_strategy_threshold
    - 7.361296528960423
  - - reward_threshold
    - 400
  - - target_kl
    - 0.01
