!!python/object/apply:collections.OrderedDict
- - - activation_fn
    - tanh
  - - batch_size
    - 8
  - - buffer_alpha
    - 0.7537904652377069
  - - buffer_capacity
    - 5000
  - - cg_max_steps
    - 5
  - - entropy_coef
    - 0.20999999999999996
  - - epsilon
    - 0.2
  - - gae_lambda
    - 1
  - - gamma
    - 0.99
  - - learning_rate
    - 0.27153527710113784
  - - n_critic_updates
    - 10
  - - n_envs
    - 8
  - - n_steps
    - 256
  - - n_timesteps
    - 900000
  - - net_arch
    - medium
  - - normalize_advantage
    - 1
  - - orthogonal_init
    - 1
  - - policy
    - MlpPolicy
  - - sampling_coef
    - 0.56
  - - target_kl
    - 0.05
