!!python/object/apply:collections.OrderedDict
- - - activation_fn
    - tanh
  - - batch_size
    - 256
  - - cg_max_steps
    - 20
  - - gae_lambda
    - 1
  - - gamma
    - 0.999
  - - learning_rate
    - 0.0013728588534608977
  - - n_critic_updates
    - 10
  - - n_envs
    - 8
  - - n_steps
    - 256
  - - n_timesteps
    - 100000
  - - net_arch
    - small
  - - policy
    - MlpPolicy
  - - reward_threshold
    - 450
  - - target_kl
    - 0.02
  - - use_per
    - false
