Ant-v5:
  trial_number: 25
  value: 998.8176276
  params:
    n_steps: 128
    gamma: 0.8
    learning_rate: 0.012901307985226144
    n_critic_updates: 30
    cg_max_steps: 5
    target_kl: 0.005
    gae_lambda: 0.99
    batch_size: 16
    net_arch: medium
    activation_fn: relu
    entropy_coeff: 0.6500000000000001
    buffer_capacity: 84000
    epsilon: 0.55
    orthogonal_init: 1
    n_timesteps: 200000
    n_envs: 10
  comment: 'Best trial details: _number=25, state=1, _values=[998.8176276], _datetime_start=2025-01-29
    11:14:23.640593, datetime_complete=2025-01-29 11:42:34.940715, _params={''n_steps'':
    128, ''gamma'': 0.8, ''learning_rate'': 0.012901307985226144, ''n_critic_updates'':
    30, ''cg_max_steps'': 5, ''target_kl'': 0.005, ''gae_lambda'': 0.99, ''batch_size'':
    16, ''net_arch'': ''medium'', ''activation_fn'': ''relu'', ''entropy_coeff'':
    0.6500000000000001, ''buffer_capacity'': 84000, ''epsilon'': 0.55, ''orthogonal_init'':
    True, ''n_timesteps'': 200000, ''n_envs'': 10}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    1001.8123292}, intermediate_values={1: 1001.8123292, 2: 998.8176276}, _distributions={''n_steps'':
    CategoricalDistribution(choices=(8, 16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'':
    CategoricalDistribution(choices=(0.8, 0.85, 0.9, 0.95, 0.99)), ''learning_rate'':
    FloatDistribution(high=1.0, log=True, low=1e-05, step=None), ''n_critic_updates'':
    CategoricalDistribution(choices=(5, 10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03,
    0.02, 0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8,
    0.9, 0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024)), ''net_arch'': CategoricalDistribution(choices=(''small'',
    ''medium'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coeff'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=1000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10))}, _trial_id=25'
