Ant-v5:
  trial_number: 152
  value: 3674.9342061999996
  params:
    n_steps: 128
    gamma: 0.95
    learning_rate: 0.0005263233376590863
    n_critic_updates: 10
    cg_max_steps: 25
    target_kl: 0.001
    gae_lambda: 0.9
    batch_size: 256
    net_arch: medium
    activation_fn: tanh
    ent_coef: 0.00030000000000000003
    epsilon: 0.7000000000000001
    orthogonal_init: 1
    n_timesteps: 900000
    n_envs: 2
  comment: 'Best trial details: _number=152, state=1, _values=[3674.9342061999996],
    _datetime_start=2025-01-27 11:42:35.663747, datetime_complete=2025-01-27 22:55:33.288237,
    _params={''n_steps'': 128, ''gamma'': 0.95, ''learning_rate'': 0.0005263233376590863,
    ''n_critic_updates'': 10, ''cg_max_steps'': 25, ''target_kl'': 0.001, ''gae_lambda'':
    0.9, ''batch_size'': 256, ''net_arch'': ''medium'', ''activation_fn'': ''tanh'',
    ''ent_coef'': 0.00030000000000000003, ''epsilon'': 0.7000000000000001, ''orthogonal_init'':
    True, ''n_timesteps'': 900000, ''n_envs'': 2}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    1006.3686949999999, ''completed_rung_1'': 1268.5791278000002, ''completed_rung_2'':
    1581.1223184}, intermediate_values={1: 1006.3686949999999, 2: 877.9992857999999,
    3: 1060.4047894, 4: 1268.5791278000002, 5: 1292.6892846000003, 6: 1487.9402175999999,
    7: 1485.011695, 8: 1280.9856001999997, 9: 1273.374452, 10: 1391.9795254, 11: 678.2329498,
    12: 884.254424, 13: 1624.14933, 14: 1930.7382094, 15: 2828.5045498, 16: 1581.1223184,
    17: 2739.0577356, 18: 3674.9342061999996}, _distributions={''n_steps'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8,
    0.85, 0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True,
    low=1e-05, step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02,
    0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9,
    0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024)), ''net_arch'': CategoricalDistribution(choices=(''small'',
    ''medium'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''ent_coef'': FloatDistribution(high=0.001, log=False, low=0.0, step=0.0001),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10))}, _trial_id=152'
Pendulum-v1:
  trial_number: 69
  value: -104.8914806
  params:
    n_steps: 256
    gamma: 0.85
    learning_rate: 0.00723791205999544
    n_critic_updates: 25
    cg_max_steps: 5
    target_kl: 0.1
    gae_lambda: 0.95
    batch_size: 1024
    net_arch: medium
    activation_fn: relu
    ent_coef: 0.0005
    epsilon: 0.8
    orthogonal_init: 0
    n_timesteps: 700000
    n_envs: 8
  comment: 'Best trial details: _number=69, state=2, _values=[-104.8914806], _datetime_start=2025-01-30
    23:33:54.822585, datetime_complete=2025-01-31 00:15:18.570505, _params={''n_steps'':
    256, ''gamma'': 0.85, ''learning_rate'': 0.00723791205999544, ''n_critic_updates'':
    25, ''cg_max_steps'': 5, ''target_kl'': 0.1, ''gae_lambda'': 0.95, ''batch_size'':
    1024, ''net_arch'': ''medium'', ''activation_fn'': ''relu'', ''ent_coef'': 0.0005,
    ''epsilon'': 0.8, ''orthogonal_init'': False, ''n_timesteps'': 700000, ''n_envs'':
    8}, _user_attrs={}, _system_attrs={''completed_rung_0'': -217.99419619999998,
    ''completed_rung_1'': -104.8914806}, intermediate_values={1: -217.99419619999998,
    2: -205.97634060000004, 3: -303.313651, 4: -104.8914806}, _distributions={''n_steps'':
    CategoricalDistribution(choices=(8, 16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'':
    CategoricalDistribution(choices=(0.8, 0.85, 0.9, 0.95, 0.99)), ''learning_rate'':
    FloatDistribution(high=1.0, log=True, low=1e-05, step=None), ''n_critic_updates'':
    CategoricalDistribution(choices=(5, 10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03,
    0.02, 0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8,
    0.9, 0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024)), ''net_arch'': CategoricalDistribution(choices=(''small'',
    ''medium'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''ent_coef'': FloatDistribution(high=0.001, log=False, low=0.0, step=0.0001),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10))}, _trial_id=69'
