Ant-v5:
  trial_number: 68
  value: 2252.2282554000003
  params:
    n_steps: 1024
    gamma: 0.99
    learning_rate: 0.02447080350120756
    n_critic_updates: 25
    cg_max_steps: 20
    target_kl: 0.05
    gae_lambda: 0.95
    batch_size: 256
    net_arch: medium
    activation_fn: relu
    entropy_coef: -0.020000000000000018
    sampling_coef: 0.6000000000000001
    buffer_capacity: 6000
    epsilon: 0.7000000000000001
    orthogonal_init: 0
    n_timesteps: 800000
    n_envs: 10
    normalize_advantage: 1
    buffer_alpha: 0.3441201858758436
  comment: 'Best trial details: _number=68, state=1, _values=[2252.2282554000003],
    _datetime_start=2025-02-03 07:33:06.203658, datetime_complete=2025-02-03 08:30:50.393003,
    _params={''n_steps'': 1024, ''gamma'': 0.99, ''learning_rate'': 0.02447080350120756,
    ''n_critic_updates'': 25, ''cg_max_steps'': 20, ''target_kl'': 0.05, ''gae_lambda'':
    0.95, ''batch_size'': 256, ''net_arch'': ''medium'', ''activation_fn'': ''relu'',
    ''entropy_coef'': -0.020000000000000018, ''sampling_coef'': 0.6000000000000001,
    ''buffer_capacity'': 6000, ''epsilon'': 0.7000000000000001, ''orthogonal_init'':
    False, ''n_timesteps'': 800000, ''n_envs'': 10, ''normalize_advantage'': True,
    ''buffer_alpha'': 0.3441201858758436}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    1061.9177524}, intermediate_values={1: 1061.9177524, 2: 2252.2282554000003}, _distributions={''n_steps'':
    CategoricalDistribution(choices=(8, 16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'':
    CategoricalDistribution(choices=(0.8, 0.85, 0.9, 0.95, 0.99)), ''learning_rate'':
    FloatDistribution(high=1.0, log=True, low=1e-05, step=None), ''n_critic_updates'':
    CategoricalDistribution(choices=(5, 10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03,
    0.02, 0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8,
    0.9, 0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'',
    ''medium'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=1000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10)), ''normalize_advantage'': CategoricalDistribution(choices=(True,
    False)), ''buffer_alpha'': FloatDistribution(high=1.0, log=True, low=0.1, step=None)},'
InvertedDoublePendulum-v5:
  trial_number: 424
  value: 9359.8015914
  params:
    learning_rate: 0.029030183470735587
    entropy_coef: 0.15999999999999992
    sampling_coef: -0.32999999999999996
    buffer_alpha: 0.1692367468838991
  comment: 'Best trial details: _number=424, state=1, _values=[9359.8015914], _datetime_start=2025-02-06
    16:54:00.080839, datetime_complete=2025-02-06 17:51:34.286089, _params={''learning_rate'':
    0.029030183470735587, ''entropy_coef'': 0.15999999999999992, ''sampling_coef'':
    -0.32999999999999996, ''buffer_alpha'': 0.1692367468838991}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    1794.0776984, ''completed_rung_1'': 9359.160828400001}, intermediate_values={1:
    1794.0776984, 2: 1999.6426999999999, 3: 1032.0332104000001, 4: 9359.160828400001,
    5: 9358.7250864, 6: 9359.8015914}, _distributions={''learning_rate'': FloatDistribution(high=1.0,
    log=True, low=1e-05, step=None), ''entropy_coef'': FloatDistribution(high=1.0,
    log=False, low=-1.0, step=0.01), ''sampling_coef'': FloatDistribution(high=1.0,
    log=False, low=-1.0, step=0.01), ''buffer_alpha'': FloatDistribution(high=1.0,
    log=True, low=0.1, step=None)}, _trial_id=424'
Pendulum-v1:
  trial_number: 156
  value: -123.5911666
  params:
    n_steps: 1024
    gamma: 0.99
    learning_rate: 0.14444743075224273
    n_critic_updates: 20
    cg_max_steps: 25
    target_kl: 0.005
    gae_lambda: 0.8
    batch_size: 256
    net_arch: large
    activation_fn: tanh
    entropy_coef: -0.7
    sampling_coef: -0.6799999999999999
    buffer_capacity: 36000
    epsilon: 0.85
    orthogonal_init: 0
    n_timesteps: 800000
    n_envs: 2
    normalize_advantage: 0
    buffer_alpha: 0.8287087040518522
  comment: 'Best trial details: _number=156, state=1, _values=[-123.5911666], _datetime_start=2025-02-04
    05:11:43.198200, datetime_complete=2025-02-04 05:43:37.658584, _params={''n_steps'':
    1024, ''gamma'': 0.99, ''learning_rate'': 0.14444743075224273, ''n_critic_updates'':
    20, ''cg_max_steps'': 25, ''target_kl'': 0.005, ''gae_lambda'': 0.8, ''batch_size'':
    256, ''net_arch'': ''large'', ''activation_fn'': ''tanh'', ''entropy_coef'': -0.7,
    ''sampling_coef'': -0.6799999999999999, ''buffer_capacity'': 36000, ''epsilon'':
    0.85, ''orthogonal_init'': False, ''n_timesteps'': 800000, ''n_envs'': 2, ''normalize_advantage'':
    False, ''buffer_alpha'': 0.8287087040518522}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    -96.2369776}, intermediate_values={1: -96.2369776, 2: -123.5911666}, _distributions={''n_steps'':
    CategoricalDistribution(choices=(8, 16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'':
    CategoricalDistribution(choices=(0.8, 0.85, 0.9, 0.95, 0.99)), ''learning_rate'':
    FloatDistribution(high=1.0, log=True, low=1e-05, step=None), ''n_critic_updates'':
    CategoricalDistribution(choices=(5, 10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03,
    0.02, 0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8,
    0.9, 0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256,
    512, 1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=10000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10)), ''normalize_advantage'': CategoricalDistribution(choices=(True,
    False)), ''buffer_alpha'': FloatDistribution(high=1.0, log=True, low=0.1, step=None)},
    _trial_id=156'
