Humanoid-v5:
  trial_number: 78
  value: 425.2933906
  params:
    n_steps: 64
    gamma: 0.99
    learning_rate: 0.001765494595109263
    n_critic_updates: 10
    cg_max_steps: 20
    target_kl: 0.05
    gae_lambda: 0.9
    batch_size: 256
    net_arch: large
    activation_fn: tanh
    entropy_coef: 0.14000000000000012
    sampling_coef: -0.9299999999999999
    buffer_capacity: 84000
    epsilon: 0.7000000000000001
    orthogonal_init: 1
    n_timesteps: 400000
    n_envs: 2
    normalize_advantage: 1
    buffer_alpha: 0.343423270490337
  comment: 'Best trial details: _number=78, state=1, _values=[425.2933906], _datetime_start=2025-02-07
    11:35:28.840846, datetime_complete=2025-02-07 12:13:17.875458, _params={''n_steps'':
    64, ''gamma'': 0.99, ''learning_rate'': 0.001765494595109263, ''n_critic_updates'':
    10, ''cg_max_steps'': 20, ''target_kl'': 0.05, ''gae_lambda'': 0.9, ''batch_size'':
    256, ''net_arch'': ''large'', ''activation_fn'': ''tanh'', ''entropy_coef'': 0.14000000000000012,
    ''sampling_coef'': -0.9299999999999999, ''buffer_capacity'': 84000, ''epsilon'':
    0.7000000000000001, ''orthogonal_init'': True, ''n_timesteps'': 400000, ''n_envs'':
    2, ''normalize_advantage'': True, ''buffer_alpha'': 0.343423270490337}, _user_attrs={},
    _system_attrs={''completed_rung_0'': 315.7868884, ''completed_rung_1'': 382.53918239999996,
    ''completed_rung_2'': 429.4404152}, intermediate_values={1: 315.7868884, 2: 305.83557899999994,
    3: 291.3353462, 4: 382.53918239999996, 5: 303.4738554, 6: 306.4449222, 7: 250.0747528,
    8: 402.792335, 9: 305.0334414, 10: 257.0309064, 11: 250.7797352, 12: 374.22383460000003,
    13: 473.4332066, 14: 316.3016928, 15: 251.3656664, 16: 429.4404152, 17: 444.9788546,
    18: 425.2933906}, _distributions={''n_steps'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8,
    0.85, 0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True,
    low=1e-05, step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02,
    0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9,
    0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256,
    512, 1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=10000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10)), ''normalize_advantage'': CategoricalDistribution(choices=(True,
    False)), ''buffer_alpha'': FloatDistribution(high=1.0, log=True, low=0.1, step=None)},
    _trial_id=78'
