Pendulum-v1:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: -3.0
  batch_size: 256
  n_steps: 2048
  gamma: 0.99
  gae_lambda: 0.95
  n_critic_updates: 10
  learning_rate: !!float 3e-4

# Tuned
LunarLanderContinuous-v3:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 195
  batch_size: 512
  n_steps: 256
  gamma: 0.995
  learning_rate: 0.8766740437252282
  n_critic_updates: 25
  cg_max_steps: 30
  target_kl: 0.001
  n_quantiles: 50
  truncation_threshold: 10
  n_value_networks: 5
  n_envs: 8

# Tuned
Ant-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 1000
  batch_size: 256
  n_steps: 2048
  gamma: 0.98
  learning_rate: 0.09620160300295108
  n_critic_updates: 10
  cg_max_steps: 5
  target_kl: 0.001
  n_quantiles: 50
  truncation_threshold: 5
  n_value_networks: 7
  n_envs: 8

Humanoid-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 450

# Tuned
InvertedDoublePendulum-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 410
  n_steps: 2048
  gamma: 0.995
  learning_rate: 0.0001014316039088728
  n_critic_updates: 20
  n_value_networks: 2
  penalty_coef: 0.0035623130952181737
  adaptive_truncation: True
  net_arch: medium
  activation_fn: tanh
  batch_size: 64
  n_envs: 8

RocketLander-v0:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: -3.0
  normalize: true
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3

