!!python/object/apply:collections.OrderedDict
- - - activation_fn
    - relu
  - - batch_size
    - 256
  - - buffer_alpha
    - 0.3441201858758436
  - - buffer_capacity
    - 6000
  - - cg_max_steps
    - 20
  - - entropy_coef
    - -0.020000000000000018
  - - epsilon
    - 0.7000000000000001
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 0.02447080350120756
  - - n_critic_updates
    - 25
  - - n_envs
    - 10
  - - n_steps
    - 1024
  - - n_timesteps
    - 800000
  - - net_arch
    - medium
  - - normalize_advantage
    - 1
  - - orthogonal_init
    - 0
  - - policy
    - MlpPolicy
  - - sampling_coef
    - 0.6000000000000001
  - - target_kl
    - 0.05
