!!python/object/apply:collections.OrderedDict
- - - activation_fn
    - tanh
  - - batch_size
    - 512
  - - buffer_capacity
    - 3000
  - - cg_max_steps
    - 30
  - - ent_coef
    - 0.00030000000000000003
  - - epsilon
    - 0.4
  - - gae_lambda
    - 0.8
  - - gamma
    - 0.99
  - - learning_rate
    - 0.0009783065937853852
  - - n_critic_updates
    - 10
  - - n_envs
    - 8
  - - n_steps
    - 512
  - - n_timesteps
    - 1000000
  - - net_arch
    - medium
  - - orthogonal_init
    - 0
  - - policy
    - MlpPolicy
  - - replay_strategy_threshold
    - -2.918898840377884
  - - reward_threshold
    - 300
  - - target_kl
    - 0.01
  - - use_per
    - false
