Pendulum-v1:
  policy: "MlpPolicy"
  n_timesteps: 100000
  reward_threshold: -3.0

LunarLanderContinuous-v3:
  policy: "MlpPolicy"
  n_timesteps: 100000
  reward_threshold: 195

Ant-v5:
  policy: "MlpPolicy"
  n_timesteps: 100000
  reward_threshold: 1000
  batch_size: 128
  n_steps: 256
  gamma: 0.95
  learning_rate: 0.0007291778429655199
  ent_coef: 1.9036008616760693e-08
  clip_range: 0.3
  n_epochs: 10
  gae_lambda: 1.0
  max_grad_norm: 0.5
  vf_coef: 0.8262092832719824
  net_arch: small
  activation_fn: relu

# Tuned
Humanoid-v5:
  policy: "MlpPolicy"
  n_timesteps: 100000
  batch_size: 32
  n_steps: 1024
  gamma: 0.9999
  learning_rate: 5.952941145071963e-05
  ent_coef: 0.09916620755875631
  clip_range: 0.1
  n_epochs: 5
  gae_lambda: 0.9
  max_grad_norm: 0.8
  vf_coef: 0.6478550290553781
  net_arch: medium
  activation_fn: tanh
  reward_threshold: 450

# Tuned
InvertedDoublePendulum-v5:
  policy: "MlpPolicy"
  n_timesteps: 100000
  batch_size: 8
  n_steps: 512
  gamma: 0.99
  learning_rate: 0.0002076880765596658
  ent_coef: 0.0022800737277672723
  clip_range: 0.4
  n_epochs: 5
  gae_lambda: 0.8
  max_grad_norm: 0.7
  vf_coef: 0.8335472464784038
  net_arch: medium
  activation_fn: tanh
  reward_threshold: 410

RocketLander-v0:
  policy: "MlpPolicy"
  n_timesteps: 100000
  reward_threshold: -3.0