# Tuned
Pendulum-v1:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: -3.0
  n_steps: 1024
  gamma: 0.9
  n_critic_updates: 15
  use_sde: True
  sde_sample_freq: 4

# Tuned
LunarLanderContinuous-v3:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 195
  batch_size: 32
  n_steps: 2048
  gamma: 0.995
  learning_rate: 0.0014
  n_critic_updates: 20
  cg_max_steps: 25
  target_kl: 0.01
  gae_lambda: 0.92
  net_arch: medium
  activation_fn: relu
  n_envs: 8

# Tuned
Ant-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 1000
  batch_size: 16
  n_steps: 32
  gamma: 0.9
  learning_rate: 0.00011660060746654879
  n_critic_updates: 5
  cg_max_steps: 30
  target_kl: 0.001
  gae_lambda: 0.92
  net_arch: small
  activation_fn: relu
  n_envs: 2

# Tuned
Humanoid-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 256
  n_steps: 32
  gamma: 0.999
  learning_rate: 0.07439215571634901
  n_critic_updates: 20
  cg_max_steps: 5
  target_kl: 0.02
  gae_lambda: 0.92
  net_arch: small
  activation_fn: tanh
  reward_threshold: 450
  n_envs: 8

# Tuned
InvertedDoublePendulum-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 410
  batch_size: 256
  n_steps: 512
  gamma: 0.95
  learning_rate: 0.002726187365030899
  n_critic_updates: 5
  cg_max_steps: 25
  target_kl: 0.03
  gae_lambda: 0.99
  net_arch: medium
  activation_fn: relu
  n_envs: 8

# Tuned
RocketLander-v0:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: -3.0
  batch_size: 32
  n_steps: 1024
  gamma: 0.999
  learning_rate: 1.1367854351821837e-05
  n_critic_updates: 25
  cg_max_steps: 20
  target_kl: 0.05
  gae_lambda: 0.92
  net_arch: small
  activation_fn: relu

