Pendulum-v1:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: -3.0
  batch_size: 256
  n_steps: 2048
  gamma: 0.99
  gae_lambda: 0.95
  n_critic_updates: 10
  learning_rate: !!float 3e-4

# Tuned
LunarLanderContinuous-v3:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 195
  batch_size: 8
  n_steps: 2048
  gamma: 0.995
  learning_rate: !!float 4.7615e-05
  n_critic_updates: 30
  cg_max_steps: 5
  target_kl: 0.001
  n_quantiles: 50
  truncation_threshold: 20
  n_value_networks: 5
  adaptive_truncation: True
  penalty_coef: 0.0026
  n_envs: 8

# Tuned
Ant-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 1000
  batch_size: 8
  n_steps: 2048
  gamma: 0.9999
  learning_rate: 4.029072520738044e-05
  n_critic_updates: 20
  cg_max_steps: 5
  target_kl: 0.001
  n_quantiles: 50
  truncation_threshold: 10
  n_value_networks: 3
  adaptive_truncation: False
  penalty_coef: 0.0013900553786711622
  n_envs: 8

Humanoid-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 450

# Tuned
InvertedDoublePendulum-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: 410
  n_steps: 1024
  gamma: 0.999
  learning_rate: 0.038357854080139184
  n_critic_updates: 10
  cg_max_steps: 30
  target_kl: 0.05
  truncation_threshold: 20
  n_value_networks: 5
  adaptive_truncation: False
  penalty_coef: 0.09663036337420812
  net_arch: small
  activation_fn: relu
  n_quantiles: 25
  n_envs: 8

RocketLander-v0:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  reward_threshold: -3.0
  normalize: true
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3

